# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x07library\"\x07\n\x05\x45mpty\"F\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\"+\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x08\x42ookList\x12#\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x14.library.BookRequest\"3\n\rBorrowRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x11\n\tmember_id\x18\x02 \x01(\x05\" \n\rReturnRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"2\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\rMemberRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"-\n\x0eMemberResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x02\n\x0eLibraryService\x12\x39\n\nCreateBook\x12\x14.library.BookRequest\x1a\x15.library.BookResponse\x12.\n\tListBooks\x12\x0e.library.Empty\x1a\x11.library.BookList\x12=\n\nBorrowBook\x12\x16.library.BorrowRequest\x1a\x17.library.ActionResponse\x12=\n\nReturnBook\x12\x16.library.ReturnRequest\x1a\x17.library.ActionResponse\x12?\n\x0c\x43reateMember\x12\x16.library.MemberRequest\x1a\x17.library.MemberResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_BOOKREQUEST']._serialized_start=35
  _globals['_BOOKREQUEST']._serialized_end=105
  _globals['_BOOKRESPONSE']._serialized_start=107
  _globals['_BOOKRESPONSE']._serialized_end=150
  _globals['_BOOKLIST']._serialized_start=152
  _globals['_BOOKLIST']._serialized_end=199
  _globals['_BORROWREQUEST']._serialized_start=201
  _globals['_BORROWREQUEST']._serialized_end=252
  _globals['_RETURNREQUEST']._serialized_start=254
  _globals['_RETURNREQUEST']._serialized_end=286
  _globals['_ACTIONRESPONSE']._serialized_start=288
  _globals['_ACTIONRESPONSE']._serialized_end=338
  _globals['_MEMBERREQUEST']._serialized_start=340
  _globals['_MEMBERREQUEST']._serialized_end=384
  _globals['_MEMBERRESPONSE']._serialized_start=386
  _globals['_MEMBERRESPONSE']._serialized_end=431
  _globals['_LIBRARYSERVICE']._serialized_start=434
  _globals['_LIBRARYSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
